### ISSUE TITLE
How to train a multitask model?

### ISSUE THREAD

**Issue by ycwang1997** [mit-han-lab/bevfusion#263]
Hello,

Thanks for your great work! I want to train a camera-only multitask model for det and seg tasks. Could you release the multitask configs and pretrained models?
Thank you.

**Comment by kentang-mit** [comment]
See https://github.com/mit-han-lab/bevfusion/issues/252. We do not release the multi-task configs and pretrained models for now because none of them achieve as good results as single-task models. You are welcomed to do some explorations on this direction.

**Comment by ycwang1997** [comment]
Thanks for your reply.
I specified the configuration in `bevfusion/configs/nuscenes/det/default.yaml`, like
```
model:
  type: BEVFusion
  encoders: null
  fuser: null
  heads:
    map: 
      type: BEVSegmentationHead
      in_channels: 256
      grid_transform:
        input_scope: [[-51.2, 51.2, 0.8], [-51.2, 51.2, 0.8]]
        output_scope: [[-50, 50, 0.5], [-50, 50, 0.5]]
      classes: ${map_classes}
      loss: focal
```
I use 4 GPUs(A6000) to train the model by runing the follow:
`torchpack dist-run -np 4 python tools/train.py configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth`

However, the losses became **nan** suddenly after training 5 epochs.
![image](https://user-images.githubusercontent.com/69711977/207108929-eff8469b-c889-41d5-bc1c-9dd2d59bc156.png)

I have tried to train again, but the same problem occured after training 4 epochs.
Could you please help me with the problem?
Thank you.
