### ISSUE TITLE
about changing backbone

### ISSUE THREAD

**Issue by hollow-503** [mit-han-lab/bevfusion#294]
@kentang-mit Thanks for your work!
Could you tell me how you modified the `pointpillars` to adapt to your coordinates?
As mentioned above, I want to change the backbone to [sstv2](https://github.com/tusen-ai/SST). However, it used `dynamic_voxelize` instead of `hard_voxelize`. Therefore, I used the voxelization implementation of `sstv2` repo. I checked the #287 and modified the `scatter` of sstv2 from
```
indices = this_coors[:, 3] * ny + this_coors[:, 2]
```
to
```
indices = this_coors[:, 2] * nx + this_coors[:, 3]
```
at the end of `sstv2` because your coordinate is `xyz` and the coordinate of `sstv2` is `zyx`. But it seems there are something wrong. I got `0 mAP` after 1 epoch. Could you share me the experiece how you modified the pointpillars to adapt to your coordinates?

**Comment by hollow-503** [comment]
My config is
```yaml
voxel_size: [0.5, 0.5, 8]
point_cloud_range: [-50, -50, -5, 50, 50, 3]

model:
  encoders:
    lidar:
      voxelize:
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: [-1, -1]
        max_num_points: -1
        Voxelization: true

      voxel_encoder:
        type: DynamicVFE
        in_channels: 5
        feat_channels: [64, 128]
        with_distance: false
        voxel_size: ${voxel_size}
        with_cluster_center: true
        with_voxel_center: true
        point_cloud_range: ${point_cloud_range}
      
      middle_encoder:
        type: SSTInputLayerV2
        window_shape: [16, 16, 1]
        sparse_shape: [200, 200, 1]
        shuffle_voxels: true
        debug: true
        pos_temperature: 10000
        normalize_pos: false
        mute: true

      backbone:
        type: SSTv2
        d_model: [128, 128, 128, 128, 128, 128, 128, 128]
        nhead: [8, 8, 8, 8, 8, 8, 8, 8]
        num_blocks: 8
        dim_feedforward: [256, 256, 256, 256, 256, 256, 256, 256]
        output_shape: [200, 200]
        num_attached_conv: 3
        conv_in_channel: 128
        conv_out_channel: 128
        debug: true

  heads:
    object:
      train_cfg:
        grid_size: [1600, 1600, 1]
      test_cfg:
        grid_size: [1600, 1600, 1]
```
The coords of `voxelize`, `voxel_encoder`, `middle_encoder`, `backbone` are all zyx. I just modified the code of converting learned features from dense tensor to sparse pseudo image (bev feature).
