### ISSUE TITLE
BEVGridTransform for different canvas sizes

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/bevfusion#468]
Thank you for the amazing work. It seems so extensible and I am able to run many experiments on this architecture.
I had some clarifying questions on the [BEVGridTransform](https://github.com/mit-han-lab/bevfusion/blob/cfc1acb42a9d6590a7cbd5a27f648aaec08febb6/mmdet3d/models/heads/segm/vanilla.py#L47) class and its parameters `grid_transform`
```yaml
grid_transform:
    input_scope: [[-51.2, 51.2, 0.8], [-51.2, 51.2, 0.8]]
    output_scope: [[-50, 50, 0.5], [-50, 50, 0.5]]
```

From what I understand the `output_scope` above generates a `200x200` size canvas. 
Does that canvas represent -50 to +50 meters with 0.5m cells?
Would it be conceptually different using `[[-50, 50, 0.5], [-50, 50, 0.5]]` vs `[[-100, 100, 1.0], [-100, 100, 1.0]]` ?
Also, how are the values for the `input_scope` determined? 
For my problem statement, I am using my custom lidar and I want to generate a canvas of size `80x200` representing 80mx200m around my ego
