### ISSUE TITLE
How to change the lidar backbone to pointpillars

### ISSUE THREAD

**Issue by wyf0414** [mit-han-lab/bevfusion#613]
I'm running the fusion model. And I want to change the lidar backbone from voxelnet to pointpillars.
I modified the configs, but it didn't work.

I hope to receive your help.

**Comment by zhijian-liu** [comment]
Could you provide more details about why "it didn't work"?

**Comment by wyf0414** [comment]
I modified the [https://github.com/mit-han-lab/bevfusion/blob/main/configs/nuscenes/det/transfusion/secfpn/camera%2Blidar/default.yaml](url).

```
    lidar:
      voxelize_reduce: false
      voxelize:
        max_num_points: 20
        point_cloud_range: ${point_cloud_range}
        voxel_size: ${voxel_size}
        max_voxels: ${max_voxels}
      backbone:
        type: PointPillarsEncoder
        pts_voxel_encoder:
          type: PillarFeatureNet
          in_channels: 5
          feat_channels: [64, 64]
          with_distance: false
          point_cloud_range: ${point_cloud_range}
          voxel_size: ${voxel_size}
          norm_cfg:
            type: BN1d
            eps: 1.0e-3
            momentum: 0.01
        pts_middle_encoder:
          type: PointPillarsScatter
          in_channels: 64
          output_shape: [512, 512]
```
I changed the lidar backbone and added conv2d and interpolate in [https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/backbones/pillar_encoder.py#L244](url) to resize the tensor to fit the fusion model.
```
@BACKBONES.register_module()
class PointPillarsEncoder(nn.Module):
    def __init__(
        self,
        pts_voxel_encoder: Dict[str, Any],
        pts_middle_encoder: Dict[str, Any],
        **kwargs,
    ):
        super().__init__()
        self.pts_voxel_encoder = build_backbone(pts_voxel_encoder)
        self.pts_middle_encoder = build_backbone(pts_middle_encoder)
        self.conv1 = nn.Conv2d(64, 256, kernel_size=3, stride=1, padding=1)  # added

    def forward(self, feats, coords, batch_size, sizes):
        # feats: [[30000, 20, 5]]   coords: [30000, 4]  sizes: [30000]
        
        batch_size = batch_size.item()
        x = self.pts_voxel_encoder(feats, sizes, coords)
        x = self.pts_middle_encoder(x, coords, batch_size)  # [1, 64, 512, 512]
        # import pdb;pdb.set_trace()
        x = self.conv1(x)
        x = F.interpolate(x, size=(180, 180), mode='bilinear', align_corners=False)
        return x
```
It can run, but got 0 mAP.
I know my way is too rough, so I'm thinking how to improve it.

Can you share some experience?
Thanks very much!
